### ISSUE TITLE
Two Questions about QTextEdit

### ISSUE THREAD

**Issue by Liskelleo** [yjg30737/pyqt-dark-notepad#2]
Emm, now I have two question about QTextEdit: 
1) How to set limitation of the total number of characters, just like the `setMaxLength` method in QLineEdit. I've written one function below; however, it doesn't meet my idea so well because I want to let users only can press 'Backspace' key when the limitation being exceeded instead of using `setText` method to achieve that goal.
```
def setMaxLength(self, maxLength: int):
    textContent = self.toPlainText()
    length = len(textContent)
    textCursor = self.textCursor()
    if length > maxLength:
        text_valid = textContent[:maxLength]
        self.clear()
        self.setText(text_valid)
        self.setTextCursor(textCursor)
```
2) How to consider the limitation mentioned above properly when using the paste shortcut. Related codes are shown below, my idea is to only paste partial content in clipboard to meet the characteristic limitation of QTextEdit (like, there are 200 chars in the string of the clipboard, and currently there're 250 in QTextEdit, in order to meet the limitation of 300 when users choose to paste, only the first 50 of 250 in the string can be pasted to the QTextEdit); however, it doesn't even work well for me.
```
#code in 'KeyPressEvent' function
elif e.matches(QKeySequence.Paste):
    textContent = QApplication.clipboard().text()
    limit = maxLength - len(self.toPlainText())
    if len(textContent) > limit:
        textContent = textContent[:limit]
```
If you have any good advice for me, don't hesitate to tell me. Looking forward to your early reply^^

**Comment by yjg30737** [comment]
This will work:

https://gist.github.com/yjg30737/53cd9d493108829fe3f257a36a2d9dc1

**Comment by Liskelleo** [comment]
Thank you! How about the second question? It seems that my codes above didn't work well, either.

**Comment by yjg30737** [comment]
My code in gist can also handle the second question.

Write some gibberish, and paste something. If it doesn't work, please tell me. To me it works like a charm

**Comment by Liskelleo** [comment]
Yikes! It works as fine as you said. I appreciate that very much.
